val_UA_V        = 'meter1_ua_v'
val_UA_P        = 'meter1_ua_p'
val_UB_V        = 'meter1_ub_v'
val_UB_P        = 'meter1_ub_p'
val_UC_V        = 'meter1_uc_v'
val_UC_P        = 'meter1_uc_p'
val_FERQ        = 'meter1_freq'
val_TEMP        = 'meter1_temp'

val_UA_V        = 'meter2_ua_v'
val_UA_P        = 'meter2_ua_p'
val_UB_V        = 'meter2_ub_v'
val_UB_P        = 'meter2_ub_p'
val_UC_V        = 'meter2_uc_v'
val_UC_P        = 'meter2_uc_p'
val_FERQ        = 'meter2_freq'
val_TEMP        = 'meter2_temp'
